sudo: false
language: node_js
- node_js: "8.9.4"

branches:
	- master
	
before_script:
	- npm install -g @angular_cli

script:
	ng build --prod

notification:
	email:
	on_failure: change
	on_success: change