dist: trusty
sudo: false

addons:
  chrome: stable

language: node_js
node_js: stable

cache:
  directories:
     - ./node_modules

stages:
  - build
  - name: optional
    if: (NOT type IN (pull_request)) AND (branch = master)

matrix:
  fast_finish: true
  allow_failures:
    - env: nightly
    - env: node9
  include:
    # Build stage
    - script: npm run build
      env: build

install:
  - npm install -g npm@5.8.0
  - npm install -g angular/cli